### ISSUE TITLE
Cannot find module 'import-sort-style-module-alias-x'

### ISSUE THREAD

**Issue by dkoprowski** [fsmaia/import-sort-style-module-alias#9] opened 2021-03-25 15:25 UTC
Hi, I have fresh install of my project on a new machine and suddenly import-sort stopped working. In the output log I see this:

```bash
3/25/2021, 4:16:30 PM:
----------------------
Cannot find module 'import-sort-style-module-alias-x'
Require stack:
- /Users/danielkoprowski/.vscode/extensions/amatiasq.sort-imports-6.2.4/out/config-cache.js
- /Users/danielkoprowski/.vscode/extensions/amatiasq.sort-imports-6.2.4/out/sort.js
- /Users/danielkoprowski/.vscode/extensions/amatiasq.sort-imports-6.2.4/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
```

This is my `importSort` in `package.json`.

```json
  "importSort": {
    ".js, .jsx, .es6, .es": {
      "parser": "babylon",
      "style": "module-alias",
      "options": {
        "alias": [
          "~~test",
          "~assets",
          "~components",
          "~config",
          "~consts",
          "~ducks",
          "~helpers",
          "~hooks",
          "~routes",
          "~scenes",
          "~services"
        ],
        "overrideBuiltinModules": true
      }
    },
    ".ts, .tsx": {
      "parser": "typescript",
      "style": "module-alias",
      "options": {
        "alias": [
          "~~test",
          "~assets",
          "~components",
          "~config",
          "~consts",
          "~ducks",
          "~helpers",
          "~hooks",
          "~routes",
          "~scenes",
          "~services"
        ]
      }
    }
  }
```

Everything is freshly installed. Strange that it doesn't work out-of-the-box. Do you have any ideas?

**Comment by fsmaia** [comment] 2021-03-25 15:28
No idea so far!

What is the import-sort version?

**Comment by dkoprowski** [comment] 2021-03-26 08:56
VS Code extensions:
```
sort-imports amatiasq.sort-imports VSC Sort Import
v6.2.4
```

And packages:
```
    "import-sort-parser-typescript": "^6.0.0",
    "import-sort-style": "^6.0.0",
    "import-sort-style-module-alias": "^1.1.0",
```

**Comment by fsmaia** [comment] 2021-03-26 15:26
Could you try running the import-sort CLI standalone so we can find out if the problem is on the VSCode extension or the import-sort itself?

```bash
npx import-sort [FILE]
```

**Comment by dkoprowski** [comment] 2021-03-27 13:56
Well `npx import-sort [FILE]` complained about `npm ERR! could not determine executable to run` but I've managed to make it work by using:

```
npx import-sort-cli [FILE]
```

It worked well so it seems like bug in the extension.

**Comment by fsmaia** [comment] 2021-03-30 18:32
Would you like to close the issue, or keep it open until we find the root cause? It's your call :)

**Comment by dkoprowski** [comment] 2021-04-10 18:42
@fsmaia I think this is an issue with the plugin itself. So it would be clean to close on this repo as sorting with CLI works well.

**Closed as completed** 2021-04-12 14:54 UTC
